### ISSUE TITLE
Roles.yaml reflect without logout/login

### ISSUE THREAD

**Issue by smalak1** [crystaldeveloper2017/Frameworkpackage#39]
Whenever there is a change in role, we have to logout and login again for it to reflect

**Comment by Adnan-Jindani** [comment]
https://github.com/crystaldeveloper2017/SSEGPLV2/commit/6a6ae2a133d596175ad699d288ddca4a9582f1f1

**Comment by crystaldeveloper2017** [comment]
Can you add these changes in the Below Projects
- [x] SSEGPLV2
- [x] HisaabCloud
- [x] SKPSecurityGate
- [x] SocietyMaintenence
- [x] AGSERP

Also a shortcut to do this would be a great enhencement.
Maybe "Alt Shift R" should reload Session and so we can see the changes very quickly.
