### ISSUE TITLE
Make Framework as Lib as part of a maven repository

### ISSUE THREAD

**Issue by Adnan-Jindani** [crystaldeveloper2017/Frameworkpackage#6]

**Comment by Adnan-Jindani** [comment]
As part of migration to maven, we need a way to fix dependency of framework libraries.
For that, one approach would be to convert the current jar into a dependency which can be injected in any of the projects.
that way we wont need the framework project running on every developer machine

Actually a comment by @crystaldeveloper2017

**Comment by crystaldeveloper2017** [comment]
Holding the migration to maven
