### ISSUE TITLE
Create New Properties file For Application Related Properties (ERAMapping.properties)

### ISSUE THREAD

**Issue by Adnan-Jindani** [crystaldeveloper2017/Frameworkpackage#8]
This properties file will contain

 

- [ ] List of Elements
- [ ]  List of Bypassed Actions
- [ ]  List of Roles

**Comment by Adnan-Jindani** [comment]
https://stackabuse.com/reading-and-writing-yaml-files-in-java-with-snakeyaml/

**Comment by crystaldeveloper2017** [comment]
Resolved
